const DEFAULT_ENVIRONMENT = 'local';
const DEFAULT_DOMAIN = 'localhost:3000';
const DEFAULT_SOCKET_SERVER_DOMAIN = 'http://localhost:8000';
const DEFAULT_API_PREFIX = '/api';

const DEFAULT_ACCESS_ALLOWED_ORIGINS = ['http://localhost:3001'];

/** NOTE: Util for ACCESS_ALLOWED_ORIGINS */
const getAccessAllowedOrigins = () => {
  if (!process.env.ACCESS_ALLOWED_ORIGINS) return DEFAULT_ACCESS_ALLOWED_ORIGINS;

  const parsedAccessAllowedOrigins = JSON.parse(process.env.ACCESS_ALLOWED_ORIGINS);

  if (!Array.isArray(parsedAccessAllowedOrigins)) return DEFAULT_ACCESS_ALLOWED_ORIGINS;

  return parsedAccessAllowedOrigins as string[];
};

/** NOTE: Backend Settings */
export const SERVER_SETTINGS = {
  // Project
  ENVIRONMENT: process.env.ENVIRONMENT ?? DEFAULT_ENVIRONMENT,
  DOMAIN: process.env.DOMAIN ?? DEFAULT_DOMAIN,
  API_PREFIX: process.env.API_PREFIX ?? DEFAULT_API_PREFIX,
  CRYPTION_SALT_ROUND: process.env.CRYPTION_SALT_ROUND,
  ACCESS_TOKEN_JWT_SECRET: process.env.ACCESS_TOKEN_JWT_SECRET,
  REFRESH_TOKEN_JWT_SECRET: process.env.REFRESH_TOKEN_JWT_SECRET,
  ACCESS_ALLOWED_ORIGINS: getAccessAllowedOrigins(),

  // Database
  DATABASE_URL: process.env.DATABASE_URL,

  // Socket Server
  SOCKET_SERVER_DOMAIN: process.env.SOCKET_SERVER_DOMAIN ?? DEFAULT_SOCKET_SERVER_DOMAIN,
  SOKCET_SERVER_API_PREFIX: process.env.SOKCET_SERVER_API_PREFIX,

  // OAuth
  KAKAO_CLIENT_ID: process.env.KAKAO_CLIENT_ID,
  KAKAO_CLIENT_SECRET: process.env.KAKAO_CLIENT_SECRET,
  NAVER_CLOUD_PLATFORM_ACCESS_KEY_ID: process.env.NAVER_CLOUD_PLATFORM_ACCESS_KEY_ID,
  NAVER_CLOUD_PLATFORM_SECRET_KEY: process.env.NAVER_CLOUD_PLATFORM_SECRET_KEY,
  NAVER_CLOUD_PLATFORM_SENS_SERVICE_ID: process.env.NAVER_CLOUD_PLATFORM_SENS_SERVICE_ID,

  // Outer API
  NAVER_CLOUD_PLATFORM_SENS_SERVICE_PHONENUMBER:
    process.env.NAVER_CLOUD_PLATFORM_SENS_SERVICE_PHONENUMBER,
} as const;

/** NOTE: Client Settings */
export const CLIENT_SETTINGS = {
  ENVIRONMENT: process.env.NEXT_PUBLIC_ENVIRONMENT ?? DEFAULT_ENVIRONMENT,
  DOMAIN: process.env.NEXT_PUBLIC_DOMAIN ?? DEFAULT_DOMAIN,
  SOCKER_SERVER_DOMAIN:
    process.env.NEXT_PUBLIC_SOCKET_SERVER_DOMAIN ?? DEFAULT_SOCKET_SERVER_DOMAIN,
  SOCKET_SERVER_API_PREFIX: process.env.NEXT_PUBLIC_SOCKET_SERVER_API_PREFIX,
  API_PREFIX: process.env.NEXT_PUBLIC_API_PREFIX ?? DEFAULT_API_PREFIX,
} as const;
